apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php 
    spec:
      containers:
        - name: php
          image: saminbjit/tetris-dockerized:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: website-data
              mountPath: /var/www/html
      volumes:
        - name: website-data
          persistentVolumeClaim:
            claimName: php-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
